export const POKEMON_NAMES = [
  { id: 1, name: 'bulbasaur' },
  { id: 2, name: 'ivysaur' },
  { id: 3, name: 'venusaur' },
  { id: 4, name: 'charmander' },
  { id: 5, name: 'charmeleon' },
  { id: 6, name: 'charizard' },
  { id: 7, name: 'squirtle' },
  { id: 8, name: 'wartortle' },
  { id: 9, name: 'blastoise' },
  { id: 10, name: 'caterpie' },
  { id: 11, name: 'metapod' },
  { id: 12, name: 'butterfree' },
  { id: 13, name: 'weedle' },
  { id: 14, name: 'kakuna' },
  { id: 15, name: 'beedrill' },
  { id: 16, name: 'pidgey' },
  { id: 17, name: 'pidgeotto' },
  { id: 18, name: 'pidgeot' },
  { id: 19, name: 'rattata' },
  { id: 20, name: 'raticate' },
  { id: 21, name: 'spearow' },
  { id: 22, name: 'fearow' },
  { id: 23, name: 'ekans' },
  { id: 24, name: 'arbok' },
  { id: 25, name: 'pikachu' },
  { id: 26, name: 'raichu' },
  { id: 27, name: 'sandshrew' },
  { id: 28, name: 'sandslash' },
  { id: 29, name: 'nidoran' },
  { id: 30, name: 'nidorina' },
  { id: 31, name: 'nidoqueen' },
  { id: 32, name: 'nidoran' },
  { id: 33, name: 'nidorino' },
  { id: 34, name: 'nidoking' },
  { id: 35, name: 'clefairy' },
  { id: 36, name: 'clefable' },
  { id: 37, name: 'vulpix' },
  { id: 38, name: 'ninetales' },
  { id: 39, name: 'jigglypuff' },
  { id: 40, name: 'wigglytuff' },
  { id: 41, name: 'zubat' },
  { id: 42, name: 'golbat' },
  { id: 43, name: 'oddish' },
  { id: 44, name: 'gloom' },
  { id: 45, name: 'vileplume' },
  { id: 46, name: 'paras' },
  { id: 47, name: 'parasect' },
  { id: 48, name: 'venonat' },
  { id: 49, name: 'venomoth' },
  { id: 50, name: 'diglett' },
  { id: 51, name: 'dugtrio' },
  { id: 52, name: 'meowth' },
  { id: 53, name: 'persian' },
  { id: 54, name: 'psyduck' },
  { id: 55, name: 'golduck' },
  { id: 56, name: 'mankey' },
  { id: 57, name: 'primeape' },
  { id: 58, name: 'growlithe' },
  { id: 59, name: 'arcanine' },
  { id: 60, name: 'poliwag' },
  { id: 61, name: 'poliwhirl' },
  { id: 62, name: 'poliwrath' },
  { id: 63, name: 'abra' },
  { id: 64, name: 'kadabra' },
  { id: 65, name: 'alakazam' },
  { id: 66, name: 'machop' },
  { id: 67, name: 'machoke' },
  { id: 68, name: 'machamp' },
  { id: 69, name: 'bellsprout' },
  { id: 70, name: 'weepinbell' },
  { id: 71, name: 'victreebel' },
  { id: 72, name: 'tentacool' },
  { id: 73, name: 'tentacruel' },
  { id: 74, name: 'geodude' },
  { id: 75, name: 'graveler' },
  { id: 76, name: 'golem' },
  { id: 77, name: 'ponyta' },
  { id: 78, name: 'rapidash' },
  { id: 79, name: 'slowpoke' },
  { id: 80, name: 'slowbro' },
  { id: 81, name: 'magnemite' },
  { id: 82, name: 'magneton' },
  { id: 83, name: "farfetch'd" },
  { id: 84, name: 'doduo' },
  { id: 85, name: 'dodrio' },
  { id: 86, name: 'seel' },
  { id: 87, name: 'dewgong' },
  { id: 88, name: 'grimer' },
  { id: 89, name: 'muk' },
  { id: 90, name: 'shellder' },
  { id: 91, name: 'cloyster' },
  { id: 92, name: 'gastly' },
  { id: 93, name: 'haunter' },
  { id: 94, name: 'gengar' },
  { id: 95, name: 'onix' },
  { id: 96, name: 'drowzee' },
  { id: 97, name: 'hypno' },
  { id: 98, name: 'krabby' },
  { id: 99, name: 'kingler' },
  { id: 100, name: 'voltorb' },
  { id: 101, name: 'electrode' },
  { id: 102, name: 'exeggcute' },
  { id: 103, name: 'exeggutor' },
  { id: 104, name: 'cubone' },
  { id: 105, name: 'marowak' },
  { id: 106, name: 'hitmonlee' },
  { id: 107, name: 'hitmonchan' },
  { id: 108, name: 'lickitung' },
  { id: 109, name: 'koffing' },
  { id: 110, name: 'weezing' },
  { id: 111, name: 'rhyhorn' },
  { id: 112, name: 'rhydon' },
  { id: 113, name: 'chansey' },
  { id: 114, name: 'tangela' },
  { id: 115, name: 'kangaskhan' },
  { id: 116, name: 'horsea' },
  { id: 117, name: 'seadra' },
  { id: 118, name: 'goldeen' },
  { id: 119, name: 'seaking' },
  { id: 120, name: 'staryu' },
  { id: 121, name: 'starmie' },
  { id: 122, name: 'mr. mime' },
  { id: 123, name: 'scyther' },
  { id: 124, name: 'jynx' },
  { id: 125, name: 'electabuzz' },
  { id: 126, name: 'magmar' },
  { id: 127, name: 'pinsir' },
  { id: 128, name: 'tauros' },
  { id: 129, name: 'magikarp' },
  { id: 130, name: 'gyarados' },
  { id: 131, name: 'lapras' },
  { id: 132, name: 'ditto' },
  { id: 133, name: 'eevee' },
  { id: 134, name: 'vaporeon' },
  { id: 135, name: 'jolteon' },
  { id: 136, name: 'flareon' },
  { id: 137, name: 'porygon' },
  { id: 138, name: 'omanyte' },
  { id: 139, name: 'omastar' },
  { id: 140, name: 'kabuto' },
  { id: 141, name: 'kabutops' },
  { id: 142, name: 'aerodactyl' },
  { id: 143, name: 'snorlax' },
  { id: 144, name: 'articuno' },
  { id: 145, name: 'zapdos' },
  { id: 146, name: 'moltres' },
  { id: 147, name: 'dratini' },
  { id: 148, name: 'dragonair' },
  { id: 149, name: 'dragonite' },
  { id: 150, name: 'mewtwo' },
  { id: 151, name: 'mew' }
] as const;

  type ImagesType = {
    [key: number]: any;
  };

  export const images: ImagesType = {
    1: require('../assets/1.png'),
    2: require('../assets/2.png'),
    3: require('../assets/3.png'),
    4: require('../assets/4.png'),
    5: require('../assets/5.png'),
    6: require('../assets/6.png'),
    7: require('../assets/7.png'),
    8: require('../assets/8.png'),
    9: require('../assets/9.png'),
    10: require('../assets/10.png'),
    11: require('../assets/11.png'),
    12: require('../assets/12.png'),
    13: require('../assets/13.png'),
    14: require('../assets/14.png'),
    15: require('../assets/15.png'),
    16: require('../assets/16.png'),
    17: require('../assets/17.png'),
    18: require('../assets/18.png'),
    19: require('../assets/19.png'),
    20: require('../assets/20.png'),
    21: require('../assets/21.png'),
    22: require('../assets/22.png'),
    23: require('../assets/23.png'),
    24: require('../assets/24.png'),
    25: require('../assets/25.png'),
    26: require('../assets/26.png'),
    27: require('../assets/27.png'),
    28: require('../assets/28.png'),
    29: require('../assets/29.png'),
    30: require('../assets/30.png'),
    31: require('../assets/31.png'),
    32: require('../assets/32.png'),
    33: require('../assets/33.png'),
    34: require('../assets/34.png'),
    35: require('../assets/35.png'),
    36: require('../assets/36.png'),
    37: require('../assets/37.png'),
    38: require('../assets/38.png'),
    39: require('../assets/39.png'),
    40: require('../assets/40.png'),
    41: require('../assets/41.png'),
    42: require('../assets/42.png'),
    43: require('../assets/43.png'),
    44: require('../assets/44.png'),
    45: require('../assets/45.png'),
    46: require('../assets/46.png'),
    47: require('../assets/47.png'),
    48: require('../assets/48.png'),
    49: require('../assets/49.png'),
    50: require('../assets/50.png'),
    51: require('../assets/51.png'),
    52: require('../assets/52.png'),
    53: require('../assets/53.png'),
    54: require('../assets/54.png'),
    55: require('../assets/55.png'),
    56: require('../assets/56.png'),
    57: require('../assets/57.png'),
    58: require('../assets/58.png'),
    59: require('../assets/59.png'),
    60: require('../assets/60.png'),
    61: require('../assets/61.png'),
    62: require('../assets/62.png'),
    63: require('../assets/63.png'),
    64: require('../assets/64.png'),
    65: require('../assets/65.png'),
    66: require('../assets/66.png'),
    67: require('../assets/67.png'),
    68: require('../assets/68.png'),
    69: require('../assets/69.png'),
    70: require('../assets/70.png'),
    71: require('../assets/71.png'),
    72: require('../assets/72.png'),
    73: require('../assets/73.png'),
    74: require('../assets/74.png'),
    75: require('../assets/75.png'),
    76: require('../assets/76.png'),
    77: require('../assets/77.png'),
    78: require('../assets/78.png'),
    79: require('../assets/79.png'),
    80: require('../assets/80.png'),
    81: require('../assets/81.png'),
    82: require('../assets/82.png'),
    83: require('../assets/83.png'),
    84: require('../assets/84.png'),
    85: require('../assets/85.png'),
    86: require('../assets/86.png'),
    87: require('../assets/87.png'),
    88: require('../assets/88.png'),
    89: require('../assets/89.png'),
    90: require('../assets/90.png'),
    91: require('../assets/91.png'),
    92: require('../assets/92.png'),
    93: require('../assets/93.png'),
    94: require('../assets/94.png'),
    95: require('../assets/95.png'),
    96: require('../assets/96.png'),
    97: require('../assets/97.png'),
    98: require('../assets/98.png'),
    99: require('../assets/99.png'),
    100: require('../assets/100.png'),
    101: require('../assets/101.png'),
    102: require('../assets/102.png'),
    103: require('../assets/103.png'),
    104: require('../assets/104.png'),
    105: require('../assets/105.png'),
    106: require('../assets/106.png'),
    107: require('../assets/107.png'),
    108: require('../assets/108.png'),
    109: require('../assets/109.png'),
    110: require('../assets/110.png'),
    111: require('../assets/111.png'),
    112: require('../assets/112.png'),
    113: require('../assets/113.png'),
    114: require('../assets/114.png'),
    115: require('../assets/115.png'),
    116: require('../assets/116.png'),
    117: require('../assets/117.png'),
    118: require('../assets/118.png'),
    119: require('../assets/119.png'),
    120: require('../assets/120.png'),
    121: require('../assets/121.png'),
    122: require('../assets/122.png'),
    123: require('../assets/123.png'),
    124: require('../assets/124.png'),
    125: require('../assets/125.png'),
    126: require('../assets/126.png'),
    127: require('../assets/127.png'),
    128: require('../assets/128.png'),
    129: require('../assets/129.png'),
    130: require('../assets/130.png'),
    131: require('../assets/131.png'),
    132: require('../assets/132.png'),
    133: require('../assets/133.png'),
    134: require('../assets/134.png'),
    135: require('../assets/135.png'),
    136: require('../assets/136.png'),
    137: require('../assets/137.png'),
    138: require('../assets/138.png'),
    139: require('../assets/139.png'),
    140: require('../assets/140.png'),
    141: require('../assets/141.png'),
    142: require('../assets/142.png'),
    143: require('../assets/143.png'),
    144: require('../assets/144.png'),
    145: require('../assets/145.png'),
    146: require('../assets/146.png'),
    147: require('../assets/147.png'),
    148: require('../assets/148.png'),
    149: require('../assets/149.png'),
    150: require('../assets/150.png'),
    151: require('../assets/151.png'),
  };
  
  
  export type PokemonName = (typeof POKEMON_NAMES)[number]